services:
  app:
    build:
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
      pull: true
    init: true
    volumes:
      - proxy_scraper_checker_cache:/home/app/.cache/proxy_scraper_checker
      - ./out:/home/app/.local/share/proxy_scraper_checker
      - ./config.toml:/app/config.toml
volumes:
  proxy_scraper_checker_cache:
